# Ici c'est pour un premier test 

client: 3
epoch: 1
batch_size: 32
com_round: 30
learning_rate: 0.01
is_iid: False
cfraction: 0.1
val_freq: 2  
model: "ResNet50" # Ou DenseNet121, InceptionV3, VGG16, ViT_B16, ViT_B32